version: "3.7"

# Source: https://github.com/DoTheEvo/Traefik-v2-examples#1-traefik-routing-to-various-docker-containers

services:
  traefik:
    image: "traefik:v2.1"
    container_name: "traefik"
    hostname: "traefik"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/traefik.yml:ro"

networks:
  default:
    external: true
    name: test-net
